athletesunited/athletesunited/athletes/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

from athletesunited.athletes.views import ActivationView
from athletesunited.athletes import views as athletes_views

urlpatterns = [
    url(r'^athletes/$', athletes_views.Athletes, name='Athletes'),
    url(r'^athletes/(?P<athleteslug>[-a-zA-Z0-9_]+)/$', athletes_views.AthletePage, name='athletes-views-AthletePage'),
    url(r'^follow/$', athletes_views.AthleteFollow, name='AthleteFollow'),
    url(r'^unfollow/(?P<target_id>[-a-zA-Z0-9_]+)/$', athletes_views.AthleteUnfollow, name='AthleteUnfollow'),
    url(r'^register/$', athletes_views.AthleteRegistration, name='AthleteRegistration'),
    url(r'^register/complete/$', TemplateView.as_view(template_name='registration/registration_complete.html'), name='registration_complete'),
    url(r'^activate/complete/$', TemplateView.as_view(template_name='registration/activation_complete.html'), name='registration_activation_complete'),
    url(r'^activate/(?P<activation_key>\w+)/$', ActivationView.as_view(), name='registration_activate'),
    url(r'^login/$', athletes_views.AthleteLogin, name='AthleteLogin'),
    url(r'^logout/$', athletes_views.AthleteLogout, name='AthleteLogout'),
    url(r'^password/change/$', auth_views.password_change, name='password_change'),
    url(r'^password/change/done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^password/reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password/reset/confirm/(?P<uidb64>[a-zA-Z0-9]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^password/reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^password/reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^profile/$', athletes_views.Profile, name='Profile'),
    url(r'^profile/edit/$', athletes_views.ProfileEdit, name='ProfileEdit'),
    url(r'^profile/edit/emails/$', athletes_views.ProfileEditEmails, name='ProfileEditEmails'),
    url(r'^profile/edit/setlanguage/success/$', athletes_views.ProfileEditSetLanguageSuccess, name='ProfileEditSetLanguageSuccess'),
    url(r'^profile/edit/setlocation/success/$', athletes_views.ProfileEditSetLocationSuccess, name='ProfileEditSetLocationSuccess'),
    url('', include('social.apps.django_app.urls', namespace='social')),
]

athletesunited/athletesunited/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView

from athletesunited.dev_settings import DEBUG

urlpatterns = [
    # Django
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
               
    # AU
    url('', include('athletesunited.main.urls')),
     
    # AU Athletes
    url('', include('athletesunited.athletes.urls')),

    # AU Communities
    url('', include('athletesunited.communities.urls')),
    
    # AU Mobile Landing Page
    url(r'^mobile/$', TemplateView.as_view(template_name="mobile.html")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

athletesunited/athletesunited/athletes/models.py
import re
import random
import hashlib
import datetime

from django.conf import settings
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import signals
from django.db.models.signals import post_delete, post_save
from django.db import transaction
from django.template.loader import render_to_string
from django.utils.encoding import python_2_unicode_compatible, smart_text
from django.utils.translation import ugettext_lazy as _
from stream_django.activity import Activity
from stream_django.feed_manager import feed_manager

try:
    from django.utils.timezone import now as datetime_now
except ImportError:
    datetime_now = datetime.datetime.now

SHA1_RE = re.compile('^[a-f0-9]{40}$')

# Athlete Follow
@python_2_unicode_compatible
class Follow(models.Model):
    user = models.ForeignKey(User, related_name='friends', null=True)
    target = models.ForeignKey(User, related_name='followers', null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    
    class Meta:
        unique_together = ('user', 'target')

    @classmethod
    def activity_related_models(cls):
        return ['user', 'target']
    
    @property
    def activity_object_attr(self):
        return self
    
    @property
    def activity_notify(self):
        target_feed = feed_manager.get_notification_feed(self.target_id)
        return [target_feed]

def unfollow_feed(sender, instance, **kwargs):
    feed_manager.unfollow_user(instance.user_id, instance.target_id)


def follow_feed(sender, instance, created, **kwargs):
    if created:
        feed_manager.follow_user(instance.user_id, instance.target_id)

signals.post_delete.connect(unfollow_feed, sender=Follow)
signals.post_save.connect(follow_feed, sender=Follow)


# Athlete Profile
@python_2_unicode_compatible
class Athlete(models.Model):
    user = models.OneToOneField(User)
    slug = models.SlugField(unique=True)
    avatar = models.ImageField("Profile Picture", upload_to="images/athlete/", blank=True, null=True, default='images/no-profile-photo.jpg')
    birthday = models.DateField(blank=True, null=True)
    headline = models.CharField(max_length=30, blank=True)
    bio = models.TextField(blank=True, null=True)
    web_url = models.URLField(max_length=100, blank=True)
    my_conversations = models.ManyToManyField('communities.CommunityPost', blank=True)
    communities = models.ManyToManyField('communities.Community', blank=True)
    cities = models.ManyToManyField('communities.City', blank=True)
    twitter_screenname = models.CharField(max_length=30, blank=True)
    is_verified = models.BooleanField(default=False, blank=True)
    language = models.CharField(max_length=15, blank=True, null=True)
    ip_address = models.GenericIPAddressField(_('IP address'), unpack_ipv4=True, blank=True, null=True)
    current_city = models.ForeignKey('communities.City', related_name="currentcity", blank=True, null=True)
    current_country = models.ForeignKey('communities.Country', related_name="currentcountry", blank=True, null=True)
    
    class Meta:
        verbose_name = 'Athlete'
        verbose_name_plural = 'Athletes'
    
    User.profile = property(lambda u: Athlete.objects.get_or_create(user=u)[0])
    
    def __str__(self):
        return str(self.user.username)

    def get_absolute_url(self):
        return reverse('AthletePage', kwargs={'slug': self.athleteslug})
    
    def get_full_name(self):
        return self.user.first_name + " " + self.user.last_name

    def get_url(self):
        return self.slug

# Athlete Email
@python_2_unicode_compatible
class AthleteEmail(models.Model):
    athlete = models.ForeignKey(Athlete, null=True)
    email = models.EmailField(unique=True)
    is_verified = models.BooleanField(default=False, blank=True)
    # Need Verification Procedures
    
    class Meta:
        verbose_name = 'Athlete Email'
        verbose_name_plural = 'Athlete Emails'
    
    def __str__(self):
        return str(self.email)

# Athlete Registration Manager
class RegistrationManager(models.Manager):
    """
    Custom manager for the ``RegistrationProfile`` model.
    
    The methods defined here provide shortcuts for account creation
    and activation (including generation and emailing of activation
    keys), and for cleaning out expired inactive accounts.
    
    """
    def activate_user(self, activation_key):
        """
        Validate an activation key and activate the corresponding
        ``User`` if valid.
        
        If the key is valid and has not expired, return the ``User``
        after activating.
        
        If the key is not valid or has expired, return ``False``.
        
        If the key is valid but the ``User`` is already active,
        return ``False``.
        
        To prevent reactivation of an account which has been
        deactivated by site administrators, the activation key is
        reset to the string constant ``RegistrationProfile.ACTIVATED``
        after successful activation.

        """
        # Make sure the key we're trying conforms to the pattern of a
        # SHA1 hash; if it doesn't, no point trying to look it up in
        # the database.
        if SHA1_RE.search(activation_key):
            try:
                profile = self.get(activation_key=activation_key)
            except self.model.DoesNotExist:
                return False
            if not profile.activation_key_expired():
                user = profile.user
                user.is_active = True
                user.save()
                profile.activation_key = self.model.ACTIVATED
                profile.save()
                return user
        return False
    
    def create_inactive_user(self, username, email, password,
                             site, send_email=True):
        """
        Create a new, inactive ``User``, generate a
        ``RegistrationProfile`` and email its activation key to the
        ``User``, returning the new ``User``.

        By default, an activation email will be sent to the new
        user. To disable this, pass ``send_email=False``.
        
        """
        new_user = User.objects.create_user(username, email, password)
        new_user.is_active = False
        new_user.save()

        registration_profile = self.create_profile(new_user)

        if send_email:
            registration_profile.send_activation_email(site)

        return new_user
    create_inactive_user = transaction.atomic(create_inactive_user)
    # Deprecated in Django 1.7
    # create_inactive_user = transaction.commit_on_success(create_inactive_user)

    def create_profile(self, user):
        """
        Create a ``RegistrationProfile`` for a given
        ``User``, and return the ``RegistrationProfile``.
        
        The activation key for the ``RegistrationProfile`` will be a
        SHA1 hash, generated from a combination of the ``User``'s
        username and a random salt.
        
        """
        # Deprecated in Python 3
        """
        # salt = hashlib.sha1(str(random.random())).hexdigest()[:5]
        salt = hashlib.sha1(smart_text(random.random())).hexdigest()[:5]
        username = user.username
        if isinstance(username, unicode):
            username = username.encode('utf-8')
        activation_key = hashlib.sha1(salt+username).hexdigest()
        """
        salt = hashlib.sha1(str(random.random()).encode('utf-8')).hexdigest()[:5]
        salted_username = salt + user.username
        activation_key = hashlib.sha1(salted_username.encode('utf-8')).hexdigest()
        return self.create(user=user,
                           activation_key=activation_key)
        
    def delete_expired_users(self):
        """
        Remove expired instances of ``RegistrationProfile`` and their
        associated ``User``s.
        
        Accounts to be deleted are identified by searching for
        instances of ``RegistrationProfile`` with expired activation
        keys, and then checking to see if their associated ``User``
        instances have the field ``is_active`` set to ``False``; any
        ``User`` who is both inactive and has an expired activation
        key will be deleted.
        
        It is recommended that this method be executed regularly as
        part of your routine site maintenance; this application
        provides a custom management command which will call this
        method, accessible as ``manage.py cleanupregistration``.
        
        Regularly clearing out accounts which have never been
        activated serves two useful purposes:
        
        1. It alleviates the occasional need to reset a
           ``RegistrationProfile`` and/or re-send an activation email
           when a user does not receive or does not act upon the
           initial activation email; since the account will be
           deleted, the user will be able to simply re-register and
           receive a new activation key.
        
        2. It prevents the possibility of a malicious user registering
           one or more accounts and never activating them (thus
           denying the use of those usernames to anyone else); since
           those accounts will be deleted, the usernames will become
           available for use again.
        
        If you have a troublesome ``User`` and wish to disable their
        account while keeping it in the database, simply delete the
        associated ``RegistrationProfile``; an inactive ``User`` which
        does not have an associated ``RegistrationProfile`` will not
        be deleted.
        
        """
        for profile in self.all():
            try:
                if profile.activation_key_expired():
                    user = profile.user
                    if not user.is_active:
                        user.delete()
                        profile.delete()
            except User.DoesNotExist:

athletesunited/athletesunited/athletes/templates/athlete/athlete.html
{% extends "base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block extraheader %}

{% endblock %}
{% block title %}{% trans "Athletes United" %} | {% trans "A Community of Athletes" %}{% endblock %}
{% block content %}

        <div class="content-main">
            <div class="content-header">
                <div class="content-inner">
                    
                    {% if Athlete %}
                    
                        {% if request.user != Athlete.user %}
                        
                        <form action="{% if followed %}{% url 'AthleteUnfollow' Athlete.user.id %}{% else %}{% url 'AthleteFollow' %}{% endif %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" id="id_target" name="target" value="{{ Athlete.user.id }}">
                            <input type="hidden" id="id_user" name="user" value="{{ request.user.id }} ">
                            <button type="submit" class="btn btn-primary" value="Create" />
                            {% if followed %}
                                Unfollow
                            {% else %}
                                Follow
                            {% endif %}
                            </button> 
                        </form>
                        
                        <br>
                        
                        {% else %}
                        
                        {% endif %}
                    
                        <img src="{{ Athlete.avatar.url }}" style="height: 20%; width: 20%;"><br>
                        Name: {{ Athlete.user.first_name }} {{ Athlete.user.last_name }}<br>
                        Headline: {{ Athlete.headline }} <br>
                        Bio: {{ Athlete.bio }} <br>
                        Username: {{ Athlete.user.username }}<br>
                        Birthday: {{ Athlete.birthday }}<br>
                        Public URL: {{ Athlete.slug }}<br>
                        
                    {% else %}
                        {{ AthleteError }}
                    {% endif %}

                    <br>

                    {% if AthleteCommunities %}

                        This Athlete is a member of the following communities:
                        <br><br>
                        <ul>
                        {% for AthleteCommunity in AthleteCommunities %}
                            <li>{{ AthleteCommunity }}</li>
                        {% endfor %}
                        </ul>

                    {% else %}
                        {{ CommunityError }}
                    {% endif %}
                    
                    <br>
                    
                    {% if AthleteColleges %}
                    
                        This Athlete is a member of the following colleges:
                        <br><br>
                        <ul>
                            {% for AthleteCollege in AthleteColleges %}
                            <li>{{ AthleteCollege }}</li>
                            {% endfor %}
                        </ul>
                    
                    {% else %}
                        {{ CollegeError }}
                    {% endif %}
                    
                    <br>
                    
                    This Athlete has the following recent actions:
                    
                    <br><br>
                    
                    {% load activity_tags %}
                    
                    {% for activity in activities %}
                        {% render_activity activity 'athleteprofile' %}
                    {% endfor %}
                    
                </div>
            </div>
        </div>

{% endblock %}

athletesunited/athletesunited/athletes/templates/athlete/athletelogin.html
{% extends "base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block extraheader %}

{% endblock %}
{% block title %}{% trans "Athletes United" %} | {% trans "A Community of Athletes" %}{% endblock %}
{% block content %}

        <div class="content-main">
            <div class="content-header">
                <div class="content-inner">
                    
                    {% if LoginError %}
                    
                        {{ LoginError }}
                        
                        <br><br>
                        
                        <form action="" method="post">{% csrf_token %}
                            
                            {% for field in form %}
                            {{ field.label }}
                            {{ field }}
                            {{ field.help_text }}
                            {{ field.error }}
                            <p>
                            {% endfor %}
                            
                            <input type="submit" alt="register" />
                        </form>
                    
                    {% else %}
                    
                        <form action="" method="post">{% csrf_token %}
                            
                            {% for field in form %}
                            {{ field.label }}
                            {{ field }}
                            {{ field.help_text }}
                            {{ field.error }}
                            <p>
                            {% endfor %}
                            
                            <input type="submit" alt="register" />
                        </form>
                    
                    {% endif %}
                    
                    <br>
                    
                    Forgot your password? <a href="/password/reset">Reset your password</a>.

                    <br><br>
                    
                    <a href="{% url 'social:begin' 'facebook' %}"><img src="{{ STATIC_URL }}images/social/login_with_facebook_button.png" style="" width="23%"></a>
                    
                    <br><br>
                    
                    <a href="{% url 'social:begin' 'twitter' %}"><img src="{{ STATIC_URL }}images/social/login_with_twitter_button.png" style="" width="23%"></a>
                    
                    <br><br>
                    
                    <a href="/register/">Sign up with your email</a> today.
                    
                </div>
            </div>
        </div>

        <div class="footer-main">
            <div class="footer-header">
                <div class="footer-inner">
                    
                    <footer>
                        {% include "footer.html" %}
                    </footer>
                    
                </div>
            </div>
        </div>

{% endblock %}

athletesunited/athletesunited/athletes/templates/athlete/athleteregistration.html
{% extends "base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block extraheader %}

{% endblock %}
{% block title %}{% trans "Athletes United" %} | {% trans "A Community of Athletes" %}{% endblock %}
{% block content %}

        <div class="content-main">
            <div class="content-header">
                <div class="content-inner">
                    
                {% if CanRegister == True %}
                    
                    Before you sign up, please know that we take spam very seriously.
                    
                    <br><br>
                        
                    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}

                        {% for field in form %}
                        {{ field.label }}
                        {{ field }}
                        {{ field.help_text }}
                        {{ field.errors.as_text }}
                        <p>
                        {% endfor %}
                        
                        {{ form.errors }}

                    <input type="submit" alt="register" value="Submit" />
                    </form>
                
                {% else %}
                
                    Our apologies, we currently do not offer registration for those outside the United States.

                {% endif %}
                    
                </div>
            </div>
        </div>

        <div class="footer-main">
            <div class="footer-header">
                <div class="footer-inner">
                    
                    <footer>
                        {% include "footer.html" %}
                    </footer>
                    
                </div>
            </div>
        </div>

{% endblock %}

athletesunited/athletesunited/athletes/templates/athlete/profile.html
{% extends "base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block extraheader %}

{% endblock %}
{% block title %}{% trans "Athletes United" %} | {% trans "A Community of Athletes" %}{% endblock %}
{% block content %}

        <div class="content-main">
            <div class="content-header">
                <div class="content-inner">

                Hello, you are logged in!

                <br><br>

                <a href="/profile/edit">Edit</a> your profile.

                <br><br>

                <a href="/logout">Logout</a>
                
                </div>
            </div>
        </div>

        <div class="footer-main">
            <div class="footer-header">
                <div class="footer-inner">
                    
                    <footer>
                        {% include "footer.html" %}
                    </footer>
                    
                </div>
            </div>
        </div>

{% endblock %}

athletesunited/athletesunited/athletes/templates/athlete/profileedit.html
{% extends "base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block extraheader %}

{% endblock %}
{% block title %}{% trans "Athletes United" %} | {% trans "A Community of Athletes" %}{% endblock %}
{% block content %}

        <div class="content-main">
            <div class="content-header">
                <div class="content-inner">
                    
                    This Athlete has the following email accounts linked:
                    <br><br>
                    <ul>
                        {% for AthleteEmail in AthleteEmails %}
                        <li>Email: {{ AthleteEmail }}</li>
                        {% endfor %}
                    </ul>

                    <br>
                    
                    Manage your <a href="/profile/edit/emails">emails</a>.
                    
                    <br><br>
                    
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        {% if language.code == SelectedLanguageCode %}Your currently selected language is: {{ language.name_local }}{% endif %}
                    {% endfor %}
                    
                    <br><br>
                    
                    Set My Language:
                    
                    <form action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <input name="next" type="hidden" value="/profile/edit/setlanguage/success/" />
                        <select name="language">
                            {% get_language_info_list for LANGUAGES as languages %}
                            {% for language in languages %}
                            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                                {{ language.name_local }} <!-- ({{ language.code }}) -->
                            </option>
                            {% endfor %}
                        </select>
                        <input type="submit" value="Go" />
                    </form>

                    <br>

                    <form action="" method="post" enctype='multipart/form-data'>{% csrf_token %}

                        {% for field in UserProfileUpdateForm %}
                        {{ field.label }}
                        {{ field }}
                        {{ field.help_text }}
                        {{ field.error }}
                        <p>
                        {% endfor %}
                    
                        <br>
                        Change your <a href="/password/change">password</a>.
                        <br><br>
                        
                        Your current location is set to: {{ SelectedAthleteLocation }}
                        
                        <br><br>
                        
                        Set your <a href="/profile/edit/setlocation/success/">location</a>.
                        
                        <br><br>

                        {% for field in AthleteProfileUpdateForm %}
                        {{ field.label }}
                        {{ field }}
                        {{ field.help_text }}
                        {{ field.error }}
                        <p>
                        {% endfor %}
                        <br>
                        
                    <input type="submit" alt="post" value="Update" />
                    </form>
                    
                </div>
            </div>
        </div>

        <div class="footer-main">
            <div class="footer-header">
                <div class="footer-inner">
                    
                    <footer>
                        {% include "footer.html" %}
                    </footer>
                    
                </div>
            </div>
        </div>

{% endblock %}

athletesunited/athletesunited/athletes/templates/athlete/profileeditemails.html
{% extends "base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block extraheader %}



{% endblock %}
{% block title %}{% trans "Athletes United" %} | {% trans "A Community of Athletes" %}{% endblock %}
{% block content %}

        <div class="content-main">
            <div class="content-header">
                <div class="content-inner">
                    
                    Edit Existing Emails:
                    
                    <br><br>
                    
                    <form method="post" action="">{% csrf_token %}
                        
                        {% for field in AthleteProfileEditUpdateEmailForm %}
                        {{ field.label }}
                        {{ field }}
                        {{ field.help_text }}
                        {{ field.error }}
                        <br>
                        {% endfor %}

                        <input type="submit" alt="post" name="update_emails" value="Update" />
                    </form>
                    
                    <br>
                    
                    Add a new Email:
                    
                    <br><br>
                    
                    <form method="post" action="">{% csrf_token %}
                        
                        {% for field in AthleteProfileEditAddEmailForm %}
                        {{ field.label }}
                        {{ field }}
                        {{ field.help_text }}
                        {{ field.error }}
                        <br>
                        {% endfor %}
                        
                        <input type="submit" alt="post" name="add_email" value="Submit" />
                    </form>
                    
                </div>
            </div>
        </div>

        <div class="footer-main">
            <div class="footer-header">
                <div class="footer-inner">
                    
                    <footer>
                        {% include "footer.html" %}
                    </footer>
                    
                </div>
            </div>
        </div>

{% endblock %}

athletesunited/athletesunited/athletes/templates/athlete/profileeditsetlanguagesuccess.html
{% extends "base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block extraheader %}
    <!-- Fix CSS for Datepicker -->
    <!-- <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" /> -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js" type="text/javascript" ></script>

{% endblock %}
{% block title %}{% trans "Athletes United" %} | {% trans "A Community of Athletes" %}{% endblock %}
{% block content %}

        <div class="content-main">
            <div class="content-header">
                <div class="content-inner">
                
                    Success!

                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                    {% if language.code == SelectedLanguageCode %}You have now set your language to: {{ language.name_local }}.{% endif %}
                    {% endfor %}
                    
                    <br><br>
                    
                    Go back to <a href="/profile/edit/">editing your profile</a>.

                </div>
            </div>
        </div>

        <div class="footer-main">
            <div class="footer-header">
                <div class="footer-inner">
                    
                    <footer>
                        {% include "footer.html" %}
                    </footer>
                    
                </div>
            </div>
        </div>

{% endblock %}